### ISSUE TITLE
NullPointerException when running 'tw compute-envs view -n test'

### ISSUE THREAD

**Issue by drpatelh** [seqeralabs/tower-cli#181]
This works when you provide a valid `--workspace` parameter but raises the error below if it isn't.

```console
$ tw compute-envs view -n test

java.lang.NullPointerException
        at io.seqera.tower.cli.commands.computeenvs.AbstractComputeEnvCmd.lambda$computeEnvByName$1(AbstractComputeEnvCmd.java:49)
        at java.util.Optional.orElseThrow(Optional.java:408)
        at io.seqera.tower.cli.commands.computeenvs.AbstractComputeEnvCmd.computeEnvByName(AbstractComputeEnvCmd.java:49)
        at io.seqera.tower.cli.commands.computeenvs.AbstractComputeEnvCmd.fetchComputeEnv(AbstractComputeEnvCmd.java:36)
        at io.seqera.tower.cli.commands.computeenvs.ViewCmd.exec(ViewCmd.java:40)
        at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:380)
        at io.seqera.tower.cli.commands.AbstractApiCmd.call(AbstractApiCmd.java:52)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.seqera.tower.cli.Tower.main(Tower.java:89)
```

**Comment by jordeu** [comment]
Does the compute environment `test` exists? I been able to reproduce it but only when the compute environment is not found.

**Comment by drpatelh** [comment]
Nope, it doesn't exist 👍🏽

I think there are some issues with the API at the moment. Getting loads of issues with requests via the CLI like the one below:

```
ERROR: Oops... Unable to process request - Error ID: 6ZP4NXiN6MeJq8pB241qz2
```
